name: cryp
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.7.16
  - setuptools=65.6.3
  - sqlite=3.40.1
  - wheel=0.38.4
  - pip:
    - absl-py==0.12.0
    - apache-beam==2.38.0
    - appdirs==1.4.4
    - apyori==1.1.2
    - argcomplete==2.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astunparse==1.6.3
    - attrs==21.4.0
    - avro-python3==1.10.2
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blis==0.7.7
    - bs4==0.0.1
    - cachecontrol==0.12.11
    - cached-property==1.5.2
    - cachetools==4.2.4
    - catalogue==2.0.7
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - clang==5.0
    - click==8.1.3
    - cloudpickle==2.0.0
    - cmake==3.22.4
    - colorama==0.4.4
    - contextlib2==21.6.0
    - crcmod==1.7
    - cryptography==37.0.2
    - cssselect==1.2.0
    - cycler==0.11.0
    - cymem==2.0.6
    - cython==0.29.28
    - debugpy==1.6.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dill==0.3.1.1
    - django==2.2
    - django-cleanup==4.0.0
    - django-crispy-forms==1.14.0
    - djangorestframework==3.12.4
    - dm-tree==0.1.7
    - docopt==0.6.2
    - entrypoints==0.4
    - fake-useragent==1.1.1
    - fastavro==1.4.11
    - fastjsonschema==2.15.3
    - feedparser==6.0.10
    - firebase-admin==5.2.0
    - flask==2.2.3
    - flask-cors==3.0.10
    - flatbuffers==1.12
    - fonttools==4.33.3
    - future==0.18.2
    - gast==0.4.0
    - gin-config==0.5.0
    - google-api-core==2.7.3
    - google-api-python-client==2.46.0
    - google-auth==1.35.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.1
    - google-cloud-firestore==2.5.3
    - google-cloud-storage==2.4.0
    - google-crc32c==1.3.0
    - google-pasta==0.2.0
    - google-resumable-media==2.3.3
    - googleapis-common-protos==1.56.0
    - grpcio==1.46.3
    - grpcio-status==1.46.3
    - h5py==3.1.0
    - hdfs==2.7.0
    - httplib2==0.19.1
    - idna==3.3
    - imageio==2.19.0
    - imageio-ffmpeg==0.4.7
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - imutils==0.5.3
    - ipykernel==6.4.2
    - ipython==7.33.0
    - ipython-genutils==0.2.0
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.3.0
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - kaggle==1.5.12
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - langcodes==3.3.0
    - lvis==0.5.3
    - lxml==4.8.0
    - markdown==3.3.6
    - markupsafe==2.1.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - moviepy==1.0.3
    - msgpack==1.0.4
    - murmurhash==1.0.7
    - nbclient==0.6.0
    - nbconvert==6.5.0
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - nltk==3.7
    - notebook==6.4.11
    - numpy==1.19.5
    - oauth2client==4.1.3
    - oauthlib==3.2.0
    - opencv-contrib-python==4.5.5.64
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - opt-einsum==3.3.0
    - orjson==3.6.8
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parse==1.19.0
    - parso==0.8.3
    - pathy==0.6.1
    - patsy==0.5.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.0
    - plotly==5.13.0
    - portalocker==2.4.0
    - preshed==3.0.6
    - proglog==0.1.10
    - prometheus-client==0.14.1
    - promise==2.3
    - prompt-toolkit==3.0.29
    - proto-plus==1.20.6
    - protobuf==3.20.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - py-cpuinfo==8.0.0
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pycparser==2.21
    - pydantic==1.8.2
    - pydot==1.4.2
    - pydub==0.25.1
    - pyee==8.2.2
    - pygments==2.12.0
    - pyjwt==2.4.0
    - pymongo==3.12.3
    - pyparsing==2.4.7
    - pyppeteer==1.0.2
    - pyquery==2.0.0
    - pyrsistent==0.18.1
    - pytesseract==0.3.9
    - python-dateutil==2.8.2
    - python-slugify==6.1.2
    - python3-openid==3.2.0
    - pytz==2022.1
    - pywin32==305
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzmq==22.3.0
    - regex==2022.4.24
    - requests==2.27.1
    - requests-html==0.10.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacrebleu==2.0.0
    - schedule==1.1.0
    - scikit-learn==0.23.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - seqeval==1.2.2
    - sgmllib3k==1.0.0
    - six==1.15.0
    - smart-open==5.2.1
    - social-auth-app-django==3.1.0
    - social-auth-core==3.2.0
    - soupsieve==2.3.2.post1
    - spacy==3.3.0
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - speechrecognition==3.8.1
    - sqlparse==0.4.2
    - srsly==2.4.3
    - statsmodels==0.13.2
    - tabulate==0.8.9
    - tenacity==8.2.1
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.3
    - tensorflow-addons==0.14.0
    - tensorflow-cpu==2.6.0
    - tensorflow-datasets==4.4.0
    - tensorflow-estimator==2.6.0
    - tensorflow-hub==0.12.0
    - tensorflow-metadata==1.2.0
    - tensorflow-model-optimization==0.6.0
    - tensorflow-text==2.6.0
    - termcolor==1.1.0
    - terminado==0.11.1
    - testpath==0.5.0
    - text-unidecode==1.3
    - textblob==0.15.3
    - tf-models-official==2.6.0
    - tf-slim==1.1.0
    - thinc==8.0.16
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.0.5
    - typeguard==2.12.1
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - uritemplate==3.0.1
    - urllib3==1.26.9
    - w3lib==2.1.1
    - wasabi==0.9.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websockets==10.4
    - werkzeug==2.2.3
    - widgetsnbextension==3.5.1
    - wordcloud==1.8.1
    - wrapt==1.12.1
    - yahoo-fin==0.8.9.1
    - zipp==3.5.0
