name: cryp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - click=8.0.4
  - fftw=3.3.10
  - flask=2.2.2
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - pytz=2022.7
  - readline=8.2
  - scipy=1.9.3
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.0
    - charset-normalizer==3.1.0
    - flatbuffers==23.3.3
    - gast==0.4.0
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.3
    - h5py==3.8.0
    - keras==2.8.0
    - libclang==15.0.6.1
    - markdown==3.4.1
    - numpy==1.24.2
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - opt-einsum==3.3.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.2
    - tensorflow-estimator==2.8.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wrapt==1.15.0
    - yahoo-fin==0.8.9.1
    - zipp==3.5.0
